version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  eventstore:
    image: eventstore/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
  remote_control:
    build: RemoteControl
    depends_on: 
      - eventstore
  light_bulb:
    build: LightBulb
    depends_on: 
      - eventstore
      - mongo
